### ISSUE TITLE
Linux Version

### ISSUE THREAD

**Issue by paulszczesny** [imprecision/franz-app#1]
Latest version of Linux build is showing raw code and has severe display issues. Essentially unusable in current state on Linux.
![screenshot from 2016-04-18 10 35 09](https://cloud.githubusercontent.com/assets/14341332/14613462/71b95294-0551-11e6-90f8-e0d24c15316a.png)

**Comment by imprecision** [comment]
Hi,

Just to check, did you download the latest version from the links on the official website www.meetfranz.com (or here on GitHub) or elsewhere?

What's your system (OS version, 32/64 bit, Desktop Environment (Ubuntu + Unity by the looks of it?)?

I've checked this on a few VM builds (Xubuntu/Ubuntu 14, 15) and they're OK here. If you delete the service and add it again - do you get the same behaviour?  

https://franz.zendesk.com

Thanks,
-j

**Comment by paulszczesny** [comment]
Just re-installed latest version, working well now. Thanks!
