### ISSUE TITLE
Support for Actor?

### ISSUE THREAD

**Issue by forteller** [imprecision/franz-app#11]
Hi. Thanks for the work your doing on this, and for releasing it for Linux!

I'd love it if you'd add support for Actor: https://developer.actor.im/

Thanks!

**Comment by imprecision** [comment]
Thanks! :) And thanks for the Actor tip - we'll take a look.

Cheers,
-j

**Comment by forteller** [comment]
Thanks! I linked you to the developers info, but they have a web app too: https://app.actor.im/
