### ISSUE TITLE
[Arch Linux] Skype & Hangouts & Steam Chat are broken

### ISSUE THREAD

**Issue by Mikaela** [imprecision/franz-app#14]
When I go to Skype & Hangouts & Steam Chat are broken,

* I enter my Microsoft Account to Skype username and it starts loading forever.
* I move to Hangouts and enter my username and password there.
* I move to Steam, enter username, password and Steam guard code there.

Then when I move to any of these tabs, I only see the content of the previous tab I was on.

Screenshots:
* ![](https://teleuforia.mikaela.info/K0TglEaP/file_226.jpg)
* ![](https://teleuforia.mikaela.info/9q9MZS5L/file_228.jpg)
* ![](https://teleuforia.mikaela.info/FkB3y5cS/file_230.jpg)

**Comment by Mikaela** [comment]
I remembered I have two WhatsApp accounts too and tried to add another one and it has the same issue.

**Comment by Mikaela** [comment]
Restarting Franz fixes WhatsApp, but not the others.

**Comment by imprecision** [comment]
Hi, sorry to hear you're having troubles. If you've definitely got the latest version (0.9.10) and I gather you've tried deleting the service and re-adding it? If so then the next step you could try is to delete Franz's settings folder. *But* I'd only recommend that if you're comfortable deleting folders from the (hidden) user config folder.

If you are, the safest way to do this is: open up a Terminal window and type:

xdg-open ~/.config/

A window should popup, just right-click the folder called "Franz" and click "Delete".

(You can of course do all this from the command line too if you're comfortable with that.)

Make sure you quit Franz before doing this. And if you do do this - it will delete all your settings so you will have to add all your services again.

If this doesn't help - could you let me know what DE you're running? We'll then need to spend some time testing similar envs here.

Cheers,
-Jonathan

**Comment by Mikaela** [comment]
I am on that version and it seems at least Skype has started working by itself.

I have so many services that I don't think I have the effort to remove their data as those three aren't so important to me anyway.
