### ISSUE TITLE
Portable app (for Windows)

### ISSUE THREAD

**Issue by Mikaela** [imprecision/franz-app#15]
I sometimes use other peoples devices or public devices and communication apps are my biggest trouble with them. For now I have been just pinning the most important tabs to Firefox Portable and possibly missing other discussions.

Franz would fix this issue very well if it was portable and installable to USB stick without leaving data on the PC.

I currently have the following services enabled in Franz (on Windows 10, the other issues were on Arch):
* Slack * 2
* Messenger
* WhatsApp * 2
* Telegram * 2
* Skype
* Hangouts
* Steam Chat
* Discord

11 services is just a little many to pin browser tabs and WhatsApp and Telegram web don't even allow multiple accounts without incognito mode or using another browser.

**Comment by imprecision** [comment]
Hi & thanks for the feedback. At the moment Franz creates a folder in your home preferences folder to store user data. We would need to move this before that was possible, but we'll certainly look into how it could be done.

This has been requested a couple of times recently so we're definitely going to look into it.
