### ISSUE TITLE
Can't use with proxy

### ISSUE THREAD

**Issue by cashkl** [imprecision/franz-app#2]
in my school internet. There is a proxy network. Can you pls put a proxy configuration in there?(if u do this there is 800 people is ready to use this program...)

**Comment by imprecision** [comment]
Hi,

Thanks so much for the feedback; you're not the first to request proxy support so it's very much gaining priority!

We've got a lot planned for future versions and we're evaluating what we can work into the next updates, so feedback like this is really appreciated.

Cheers, 
-Jonathan
