### ISSUE TITLE
Open Source

### ISSUE THREAD

**Issue by dimorphic** [imprecision/franz-app#4]
Hi there!

I was really happy yesterday when I stumbled upon Franz app, looking for an messenger-app-unifier. Was even more hyped when i read that it's Electron based. Good job!

But then, i was sad and disapointed to see that it's not open source and that we can't work, improve or customize it.

Any plans on open sourcing this? Pretty plx? :)

Cheers.

**Comment by imprecision** [comment]
Hi!

So glad you're finding Franz useful! :)

We're open source advocates ourselves and once we're out of beta with Franz, we'll certainly be considering options in regards to open sourcing, etc. But it's really early days yet so I hope you'll bear with us until then.

We've got a lot planned for future versions and we're evaluating what we can work into the next updates, so feedback like this is really appreciated.

Cheers,
-Jonathan

**Comment by KAMiKAZOW** [comment]
You ship LGPL code. You must ship its source as well. You also have to attribute copyright holders of BSD-licensed components.

Right now your app breaches copyrights.

**Comment by imprecision** [comment]
If you see anything you think we've missed, please do let me know and we'll fix it. It certainly isn't our intension to do anything other than the right and proper thing here. Licenses of any modules Franz uses should be respected and source code of any such modules are actually available within the app bundle itself.

**Comment by KAMiKAZOW** [comment]
For example the BSD license used by Chromium OS system API says:
"Redistributions in binary form must reproduce the above copyright notice"

Do you see anything like that here?
![116](https://cloud.githubusercontent.com/assets/3259076/14901767/550c29de-0d97-11e6-97c6-9fa7bbf2ed7b.png)
You claim to be the sole copyright holders and you're not.

If you want to use other people's work, comply with their terms. It's that easy.

**Comment by tuxflo** [comment]
I also don't understand the phrase
>  once we're out of beta with Franz, we'll certainly be considering options in regards to open sourcing, etc.

why wait until the beta is over? Open sourcing may help to get the software out of a beta stadium faster.
> Franz does not read anything you type, send or receive.

How could we know that if we can't check it by ourselves?

**Comment by imprecision** [comment]
Hi Tuxflow,

_Until beta is over:_ I must stress the word "considering", and because that's what we've decided is the best plan given the resources we have available and focus we're able to provide.

_Read anything you type, etc:_ well that's the trust you choose (or not to) put into closed source software. It's entirely your choice of course but if you choose to and are still concerned, you could run a network traffic analyser to further help prove to yourself, for example.

**Comment by imprecision** [comment]
Hi KAMiKAZOW,

So to reiterate points I've already highlighted and are also findable in the app bundle itself:

Your screen shot: I can actually very much appreciate how this is leading to ambiguity. It is very under developed and we will be turning that into a list of acknowledgements (i.e. much more more easily accessible) in the next release.

Licenses: all licenses are intact, all terms are complied with just as any other closed source Electron app is handled.

Finally, "It's that easy." - I'm so glad for you that you find this so. For the rest of us though, we are instead clearly stuck with having to go with civil behaviour, constructive communication and even fixing things when on the odd occasions we might get things wrong.

**Comment by nmaggioni** [comment]
I support the open source thought, why do you want to wait until beta is over? It will actually be more useful to open your code while you are _still_ in beta!

For example I was searching a way to start Franz minimized, but found no code to dig into. That's definitely disappointing for an application like this - even more if you've already expressed the will to disclose your source code in the future.

You can understand that the trust I put into a closed-source multi-network messaging client is nowhere near the trust I'd put in the same open-source client, and it's improvement capabilites are drastically lowered.
Most desktop messaging clients ([Telegram][1], to name one) have their source code freely available, I don't see which reason keeps an application that aggregates many of them to go the same way...

[1]: https://github.com/telegramdesktop/tdesktop

**Comment by imprecision** [comment]
Hi nmaggioni, thanks for your feedback and I understand your desires and concerns on this. Both points have been discussed further up this thread.
