### ISSUE TITLE
Whatsapp Login Problem

### ISSUE THREAD

**Issue by TheSayantan96** [imprecision/franz-app#5]
WhatsappWeb scanner cant scan the qr code given by franz...its just continue scanning...but nothing happens whereas when I am login through the browser by going web.whatsapp.com..the scanner works fine..and login immediately.

**Comment by imprecision** [comment]
Hi,

Sorry to hear you're having problems, if you could tell me a little about your operating system and version of Franz I'm sure I can help. Or perhaps if you could open a support ticket at our help desk that would be even better:

https://franz.zendesk.com

Please make sure you're using the latest version of Franz (0.9.10).

Cheers,
-Jonathan

**Comment by TheSayantan96** [comment]
I am using Franz latest version on elementary os freya 0.3.2 64 bit

**Comment by imprecision** [comment]
Have you tried deleting the service and then re-adding it? (From Franz's main screen click the little gear symbol next to the WhatsApp service and then press the "Delete Service" button.)

If that doesn't help, could you let me know your screen resolution if possible and I'll then try emulating it here.

Thanks,
-Jonathan
