### ISSUE TITLE
Irc support?

### ISSUE THREAD

**Issue by matejc** [imprecision/franz-app#6]
First of all: great app! I like the grouping of the different chat solutions in one application.

Is there a plan for IRC client or maybe even something like [Glowing Bear](https://www.glowing-bear.org/), which is a WeeChat irc client web frontend?

PS: I will be waiting for the open-sourced Franz

**Comment by imprecision** [comment]
Hi, so glad you're liking Franz!

IRC - yep we have plans in a future release soon.
Open source - we're advocates ourselves and once we're out of beta we're hoping to be in a better position to figure out what to do here.

Thanks for your feedback, cheers,
-Jonathan

**Comment by Mikaela** [comment]
Glowing Bear is WeeChat Relay client and would only work if you hosted WeeChat by yourself.

I would personally add [IRCCloud](https://irccloud.com/) and/or [KiwiIRC](https://kiwiirc.com/).

IRCCloud requires registration and the free plan has it's limits while KiwiIRC always forgets your session after quitting, but is free.

**Comment by davewongillies** [comment]
I'd love to see irccloud support for the purely selfish reason of me being a user of the service.

**Comment by imprecision** [comment]
Hi, thanks - this is really good to hear as we're trying to figure out the best first integrations for IRC. Thanks for the feedback and a release soon should have at least one of them!
