### ISSUE TITLE
linux: close window exits app, hide to systray would be more intuitive

### ISSUE THREAD

**Issue by pvanek** [imprecision/franz-app#7]
as in subject.

Any window manager operation which closed the main window leads to app quitting. From mu usecase/perspective the minimizing into systray would be more expectable

**Comment by MakuSensei** [comment]
tambien opino lo mismo
al cerrar la app, se minimice al systray en windows y linux

**Comment by imprecision** [comment]
Hi. Thanks for the feedback, we do have this issue marked as something to fix, which we're aiming to get into a future version soon.
