### ISSUE TITLE
Browser features like Search and Right-click menu.

### ISSUE THREAD

**Issue by evasconcelos** [imprecision/franz-app#8]
Is this an electron issue or can we get this features ?

I'm using 0.9.10 on linux.

**Comment by imprecision** [comment]
Hi, it's kinda Electron in that no-right-click is default and we have to add functionality in for it, but that's fine and standard practise. It's on our todo list for reasons like copy/paste/spellcheck/etc options so thanks for the "vote" - it bumps it up the list of priorities!
