### ISSUE TITLE
Portable Version?

### ISSUE THREAD

**Issue by antonio-gil** [imprecision/franz-app#9]
Hi!

Do have any plans to make the app portable? Or at least to have an option to make it portable during installation?

I don't like to install stuff on the machine at my work place, so I keep some portable apps, and I would love to have Franz in a portable way.

Thanks in advance, and best regards!

**Comment by imprecision** [comment]
Hi & thanks for the feedback. At the moment Franz creates a folder in your home preferences folder to store user data. We would need to move this before that was possible, but we'll certainly look into how it could be done.
